# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

assetic:
    bundles:
        - CampaignChainHookImageBundle
    assets:
        campaignchain_hook_image_css:
            inputs:
                - '@CampaignChainHookImageBundle/Resources/public/css/base.css'
twig:
    form:
        resources:
            - 'CampaignChainHookImageBundle:Form:fields.html.twig'