# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

services:
    campaignchain.hook.campaignchain.image:
        class: CampaignChain\Hook\ImageBundle\EntityService\ImageService
        arguments:
            - '@doctrine.orm.entity_manager'
    campaignchain.hook.form.type.campaignchain.image:
        class: CampaignChain\Hook\ImageBundle\Form\Type\ImageHookType